name: Deploy to Cloud Run

env:
  SERVICE_NAME: node-express-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: upbeat-math-410510

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # .env file is passed as build arg in Docker build
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/upbeat-math-410510/node-express-api:latest .
          docker push gcr.io/upbeat-math-410510/node-express-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/upbeat-math-410510/node-express-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
